###########

title: anshdavid.com
description: What I have been upto...
baseurl: "" #"/jekyllBear" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
# host: 0.0.0.0

#########################
# more settings

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

markdown: kramdown

compress_html:
  clippings: all
  comments: [""]
  endings:
    [
      html,
      head,
      body,
      li,
      dt,
      dd,
      rt,
      rp,
      optgroup,
      option,
      colgroup,
      caption,
      thead,
      tbody,
      tfoot,
      tr,
      td,
      th,
    ]
  profile: false
  blanklines: false
  ignore:
    envs: []

collections:
  my_tags:
    output: true
    permalink: /tagged/:slug/

defaults:
  - scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

permalink: /blog/:slug
timezone: Asia/Kolkata
future: false

exclude:
  - README.md
  - LICENSE.md
  - vendor
  - references

Blog: /blog
Fiction: /design-post

links:
  Resume: /assets/resume.pdf

special_links:
  "Search": https://duckduckgo.com
